spring:
  application:
    name: thymeleaf

  thymeleaf:
    # \u7F16\u7801\u683C\u5F0F, \u9ED8\u8BA4UTF-8
    encoding: UTF-8
  # \u5E94\u7528\u4E8E\u6A21\u677F\u7684\u6A21\u677F\u6A21\u5F0F\u3002\u53E6\u8BF7\u53C2\u9605Thymeleaf\u7684TemplateMode\u679A\u4E3E\u3002
    mode: HTML
  # \u540E\u7F00 \u9ED8\u8BA4 .html
    suffix: .html
  # \u6A21\u677F\u6587\u4EF6\u5B58\u653E\u4F4D\u7F6E  , \u9ED8\u8BA4 classpath:/templates/
    prefix: classpath:/templates/
