server:        # 服务器的端口
  port: 8081

spring:
  application:
    name: thymeleaf
  thymeleaf:
    # 是否启用模板缓存。
    cache: true
    # 是否检查模板位置是否存在。
    check-template: true
    # 是否为Web框架启用Thymeleaf视图分辨率。
    enabled: true
    # 编码格式, 默认UTF-8
    encoding: UTF-8
    # 应用于模板的模板模式。另请参阅Thymeleaf的TemplateMode枚举。
    mode: HTML
    # 前缀
    prefix: classpath:/templates/
    # 后缀
    suffix: .html
